config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about-us", to: "about#index", as: :about

  root to: "main#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
        
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> About Us </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render partial: "shared/navbar" %>
    <div class="container">  
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-item-center justify-content-center">
    <h1> Welcome to Schedule Tweet </h1>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"  %>
        </li>
      </ul>
    </div>
  </div>
</nav>